name: 'Docker Login'
description: 'Logs in to a Docker registry'
inputs:
  registry:
    description: 'Docker registry URL'
    required: true
  username:
    description: 'Docker registry username'
    required: true
  password:
    description: 'Docker registry password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Docker CLI
      run: |
        echo "${{ inputs.password }}" | docker login -u ${{ inputs.username }} --password-stdin ${{ inputs.registry }}
