name: CD

on:
    workflow_run:
        workflows:[CD]
        types: 
            - completed


jobs:

    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: docker run containers
              run: docker run -itd -p 80:80 my_life  

            - name: curl the output 
              run: curl localhost:80

              
