name: 'Install Python'

inputs:
  python_version:
    description: 'Python version to install'
    required: true
    default: '3.8'

runs:
  using: composite
  # shell: bash
  
  steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}
    # - name: Install Python
    #   shell: bash 
    #   run: |
    #     set -e

    #     # Set the environment variable to avoid debconf issues
    #     export DEBIAN_FRONTEND=noninteractive

    #       sudo apt-get update
    #       sudo apt-get purge python3 python3.*
    #       sudo apt-get install -y software-properties-common
    #       sudo add-apt-repository ppa:deadsnakes/ppa
    #       sudo apt-get update
    #       sudo apt-get install -y python${{ inputs.python_version }}
    #     # rm -rf /var/lib/apt/lists/*

         
    #      sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
    #      sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
    #      python3 --version && python3 -c "import sys; print(sys.version)"
        

    #     echo "Python installed successfully"

    
