name: 'Check Python Version'

inputs:
  p_version:
    description: 'Python version'
    required: true
    default: '3.8'  # Provide a default version if needed

runs:
  using: 'composite'
  shell: 'bash'
  steps:
    - name: Check Python version
      run: |
        sudo apt-get update
        chmod +x Maxwell134/test321/actions/python/entrypoint.sh 
        ./Maxwell134/test321/actions/python/entrypoint.sh 
