name: python version
description: ''

inputs:
    name: p version
    required: true
    type: string
    default: '3.8'

runs:
    using: 'docker'
    image: dockerfile

branding:
    icon: 'check'
    color: 'green'



    


