name: 'Check Python Version'

inputs:
  p_version:
    description: 'Python version'
    required: true
    default: '3.8'  # Provide a default version if needed

runs:
  using: 'bash'
  shell: bash
  working-directory: ${{ github.workspace }}
  steps:
    - name: Check Python version
      run: Maxwell134/test321/.github/actions/python/entrypoint.sh ${{ inputs.p_version }}
