name: 'Python Version Checker'

inputs:
  p_version:
    description: 'Python version to install'
    required: true
    default: '3.8'

runs:
  using: 'docker'
  image: Dockerfile

branding:
  icon: 'check'
  color: 'green'
