name: 'Install Python'

inputs:
  python_version:
    description: 'Python version to install'
    required: true
    default: '3.8'

runs:
  using: composite
  # shell: bash
  
  steps:
    - name: Install Python
      shell: bash 
      run: |
        set -e

        # Set the environment variable to avoid debconf issues
        export DEBIAN_FRONTEND=noninteractive

        apt-get update
        apt-get install -y python${{ inputs.python_version }}
        rm -rf /var/lib/apt/lists/*

        python3 --version
        echo "Python installed successfully"

    
