name: CD

on:
  workflow_run:
    workflows: [CI]  # Assuming CI is the name of your CI workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: docker login
        uses: Maxwell134/test321/.github/actions/login@main
        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: docker.io

      - name: check images 
        run: docker images 

      - name: pull images
        run: docker pull my_life

      - name: Start Docker container
        run: docker run -itd -p 80:80 my_life  # Replace 'my_life' with your actual Docker image

      - name: Wait for container to start
        run: sleep 10  # Adjust the sleep duration based on your application's startup time

      - name: Curl the output
        run: curl localhost:80
