name: CI

on:
    workflow_dispatch:

        inputs:
            docker_image:
                description: 'Enter docker image name' 
                type: string
                default: ubuntu
                required: true
            
            docker_tag:
                description: 'Enter the docker tag'
                type: string
                required: true

jobs:

    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Docker pull
              run:  docker pull ${{ github.event.inputs.docker_image }}:${{ github.event.inputs.docker_tag }}

            - name: Import credentials 
              uses: Docker_login_actions/.github/actions/login@main
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                registry: docker.io

            # - name: Log in to Docker Hub
            #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


              

        

            
            






        
