name: CI

on:
    workflow_dispatch:

        inputs:
            docker_image:
                description: 'Enter docker image name' 
                type: string
                default: ubuntu
                required: true
            
            docker_tag:
                description: 'Enter the docker tag'
                type: string
                required: true

jobs:

    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            # - name: Set up Docker
            #   uses: docker/login-action@master
            #   with:
            #     username: ${{ secrets.DOCKER_USERNAME }}
            #     password: ${{ secrets.DOCKER_PASSWORD }}
            #     registry: docker.io

            # - name: Import credentials 
            #   uses: Maxwell134/Docker_login_actions/.github/actions/login@main
            #   with:
            #     username: ${{ secrets.DOCKER_USERNAME }}
            #     password: ${{ secrets.DOCKER_PASSWORD }}
            #     registry: docker.io

            - name: Docker build pull
              run:  docker pull ${{ github.event.inputs.docker_image }}:${{ github.event.inputs.docker_tag }}

            - name: Docker remove images
              run: docker rmi -f $(docker images -qa)

            - name:  docker build image
              run: docker build  -t my_life:${{ github.sha }} .github/workflows

            - name: Docker images
              run: docker images
            


              

        

            
            






        
