name: CI/CD for Docker

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name'
        required: true
      image_tag:
        description: 'Docker image tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      id: docker
      set: ${{ steps.set_output.outputs }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: set_output
        run: |
          echo "::set-output name=image_name::${{ inputs.image_name }}"
          echo "::set-output name=image_tag::${{ inputs.image_tag }}"
          docker buildx build -t "${{ inputs.image_name }}:${{ inputs.image_tag }}" .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    outputs:
      
      image_name: ${{ needs.build.outputs.image_name }}
      image_tag: ${{ needs.build.outputs.image_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push "${{ inputs.image_name }}:${{ inputs.image_tag }}"
