name: Get Collaborators and Build

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Enter yes or no'
        required: true
        type: string

jobs:
  get-collaborators:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_OWNER=Maxwell134
          REPO_NAME=test321
          COLLABORATORS_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/collaborators?per_page=100"
          collaborators=$(curl -H "Authorization: token $GITHUB_TOKEN" "$COLLABORATORS_URL" | jq -r '.[].login')
          echo "Collaborators: $collaborators"

  workflow_call:
    needs: get-collaborators
    uses: Maxwell134/test321/.github/workflows/employee_validator.yaml@main
    with:
      emp_name: "${{ github.actor }}"
      prompt: ${{ github.event.inputs.prompt }}

  python_checker:
    needs: [get-collaborators, workflow_call]
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Job 1"

      - name: Actions call
        uses: Maxwell134/test321/.github/actions/python@main
        with:
          python-version: 3.9

  build:
    needs: [get-collaborators, workflow_call, python_checker]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Docker login and build
        uses: Maxwell134/Hello_world/.github/workflows/action.yml@main
