name: Get Collaborators

on:
  workflow_dispatch:

jobs:
  get-collaborators:
    runs-on: ubuntu-latest

    steps:
    - name: Get Collaborators
      run: |
        REPO_OWNER=Maxwell134
        REPO_NAME=test321
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        
        COLLABORATORS_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/collaborators"
        
        curl -H "Authorization: token $GITHUB_TOKEN" -s $COLLABORATORS_URL | jq '.[].login'
