name: Deploy to Swarm

on: [workflow_dispatch]
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set up Docker
      #   uses: docker/setup-docker@v2
      #   with:
      #     docker-version: '20.10.0'

      - name: ip info 
        run: curl ifconfig.co

      - name: Initialize Docker Swarm
        run: docker swarm init

      - name: Deploy services
        # run: docker stack deploy -c ${{ github.workspace }}/.github/workflows/docker-compose.yaml myapp
        run: docker service create --name my-nginx --publish 80:80 nginx

      - name: Docker services names
        run: |

              docker service ls 
              docker ps -a 
              docker node ls 
              curl localhost:80
              npm install -g localtunnel
              lt --port 80

              


              
     

