name: Check Employee

on:
  workflow_dispatch:
    inputs:
      emp_name:
        description: 'Employee name to check'
        required: true
        type: string

jobs:
  check_employee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Add any necessary setup or dependency installation steps here

      - name: Run check employee
        id: check_employee
        run: python3 -u ${{ github.workspace }}/.github/workflows/test.py
        env:
          employee: ${{ github.event.inputs.emp_name }}

      - name: Print result
        run: |
         result="${{ steps.check_employee.outputs.result }}"
         echo "$result"
          if [ "$result" == 'Found' ]; then
            echo "Success! Continue with additional actions."
          else
            echo "Error: Result is not 'Found'. Exiting."
            exit 1
          fi

