name: check employee
on:
  workflow_dispatch:
    inputs:
      emp_name: 
        description: ''
        type: string

jobs:
  check_employee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run check employee
        id: check_employee
        run: python3 test.py
        env:
          employee: ${{ github.event.inputs.emp_name }}

      - name: Print result
        run: echo "${{ steps.check_employee.outputs.result }}"
