name: Check Employee

on:
  workflow_dispatch:
    inputs:
      emp_name:
        description: 'Employee name to check'
        required: true
        type: string

jobs:
  check_employee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Add any necessary setup or dependency installation steps here

      - name: Run check employee
        id: check_employee
        run: python3 -u ${{ github.workspace }}/.github/workflows/test.py
        env:
          employee: ${{ github.event.inputs.emp_name }}

      - name: Print result
        run: echo "${{ steps.check_employee.outputs.result }}"
        if: steps.check_employee.outputs.result == 'Found'

  # Mark the workflow as failed if the result is not 'Found'
  
      - name: Fail workflow
        if: failure()
        run: exit 1
