name: Check Employee

on:
  # workflow_dispatch:
  workflow_call:
    inputs:
      emp_name:
        description: 'Employee name to check'
        required: true
        type: string
        
      prompt:
        description: 'Enter yes or no'
        required: true
        type: string
        

      # test-timeout:
      #   required: false
      #   type: number
      #   # default: 10

jobs:
  check_employee:
    runs-on: ubuntu-latest
    timeout-minutes: 10
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Triggered actor 
        run: echo " Github actor:${{github.actor }}"

      - name: pip install
        run: pip3 install inputimeout

      - name: Run check employee
        id: check_employee
          
        run: python3 -u ${{ github.workspace }}/.github/workflows/test.py
        env:
          employee: ${{ github.actor }}
          PROMPT: ${{ github.event.inputs.prompt }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print result
        run: |
          result="${{ steps.check_employee.outputs.result }}"
          github_actors="${{ steps.check_employee.outputs.github_actors }}"
          echo "$result"
          echo "GitHub Actors: $github_actors"
      
          if [ "$result" == 'Found' ]; then
            echo "Success! Continue with additional actions."
          else
            echo "Error: Result is not 'Found'. Exiting."
            exit 1
          fi

      - name: Hello step
        if: success()  # This step will run only if the previous step (Print result) was successful
        
        run: echo "Hello! This is the 'hello' step."
