name: Check Employee

on:
  workflow_dispatch:
    inputs:
      emp_name:
        description: 'Employee name to check'
        required: true
        type: string

      prompt:
        description: 'Enter yes or no'
        required: true
        type: boolean   

jobs:
  check_employee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: pip install
        run: pip3 install inputimeout

      # Add any necessary setup or dependency installation steps here

      - name: Run check employee
        id: check_employee
        run: python3 -u ${{ github.workspace }}/.github/workflows/test.py
        env:
          employee: ${{ github.event.inputs.emp_name }}

      - name: Print result
        # if: steps.check_employee.outputs.result == 'Found'
        # run: echo "Success! Continue with additional actions."
        run: |
         result="${{ steps.check_employee.outputs.result }}"
         echo "$result"
          if [ "$result" == 'Found' ]; then
            echo "Success! Continue with additional actions."
          else
            echo "Error: Result is not 'Found'. Exiting."
            exit 1
          fi
          
      - name: Hello step
        if: success()  # This step will run only if the previous step (Print result) was successful
        run: echo "Hello! This is the 'hello' step."

