name: Interactive Input Workflow

on:
  push:
    branches:
      - main

jobs:
  interactive-input:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set User Input
        id: set-input
        run: |
          echo "This is an interactive prompt."
          echo "Please enter your choice (yes/no):"
          echo "::set-output name=user_input::${{ env.USER_INPUT }}"
        env:
          USER_INPUT: 'yes'  # Set the default value or replace it with your logic

      - name: Use User Input
        run: |
          echo "User entered: ${{ steps.set-input.outputs.user_input }}"

      - name: Continue Workflow Based on Input
        if: steps.set-input.outputs.user_input == 'yes'
        run: |
          echo "Proceeding with additional steps..."
          # Add your additional steps here for the 'yes' case

      - name: Handle 'no' Case
        if: steps.set-input.outputs.user_input == 'no'
        run: |
          echo "Exiting workflow based on user input 'no'"
          exit 0
