name: My Workflow with Custom Script Input

on: [workflow_dispatch]
  # push:
  #   branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run custom script
        uses: actions/github-script@v5
        with:
          script: |
            const inquirer = require('inquirer');

            async function main() {
              const { proceed } = await inquirer.prompt({
                type: 'confirm',
                name: 'proceed',
                message: 'Do you want to proceed further?',
              });

              if (proceed) {
                console.log('Proceeding...');
              } else {
                console.log('Stopping workflow.');
                await github.actions.cancelWorkflowRun(context.workflowRunId);
              }
            }

            main();
