name: Create Issue Workflow

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest
    
    env:
    
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check GH Version
        run: gh --version


      - name: Create Issue
        run: |
          gh issue create -t "Confirm Docker Build" -b "Please comment with 'yes' or 'no' to confirm Docker build."
