name: External Script Workflow

on:
  workflow_dispatch

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Environment
        run: echo "Setting up environment"

      - name: Run External Script
        id: external_script
        run: |
          # Your Python script logic goes here
          python - <<EOF
          enable_check = input("Do you want to enable the blue-green check? (y/n): ")
          print(f"::set-output name=ENABLE_CHECK::{enable_check}")
          EOF

      - name: Use External Script Output
        run: echo "User chose to enable blue-green check: ${{ needs.my_job.outputs.ENABLE_CHECK }}"
