name: tom

on:
  workflow_dispatch:
    inputs:
      username: 
        description: username
        type: string
        required: true

      repo:
        description: repository name
        type: string
        required: true

      issue_number:
        description: issue
        type: string
        required: true
      
jobs:
  get-collaborators:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pip install 
        run: pip3 install requests

      - name: new action 
        uses:  Maxwell134/test321/.github/actions/tom@main
        env:
        
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
           username: ${{ github.event.inputs.username }}
           repo: ${{ github.event.inputs.repo }}
           issue_number: ${{ github.event.inputs.issue_number }}
                  
                    
      # - name: Get Collaborators
      #   id: checker
      #   run: |
        
      #     python3 -u ${{ github.workspace }}/.github/workflows/tom.py
          
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #     username: ${{ github.event.inputs.username }}
      #     repo: ${{ github.event.inputs.repo }}

      - name: Wait for 2 minutes
        run: sleep 120

      - name: Get Collaborators
        id: checker
        run: |
        
          python3 -u ${{ github.workspace }}/.github/workflows/issue.py
          
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          username: ${{ github.event.inputs.username }}
          repo: ${{ github.event.inputs.repo }}       
        
      - name: Next Steps
        if: success()
        run: echo "Successful"
