name: External Tool Workflow

on:
  issue_comment:
    types:
      - created

jobs:
  process-input:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Comment Body
        id: get-comment-body
        run: |
          COMMENT_BODY=$(jq -r .comment.body $GITHUB_EVENT_PATH)
          echo "::set-output name=comment_body::$COMMENT_BODY"

      - name: Process Comment
        run: |
          COMMENT=$"${{ steps.get-comment-body.outputs.comment_body }}"
          echo "User entered: $COMMENT"

          # Process the user input and perform necessary actions
          if [[ $COMMENT == *"yes"* ]]; then
            echo "Proceeding with additional steps..."
            # Add your additional steps here for the 'yes' case
          elif [[ $COMMENT == *"no"* ]]; then
            echo "Exiting workflow based on user input 'no'"
            exit 0
          else
            echo "Invalid input. Please enter 'yes' or 'no'."
          fi
