name: My Workflow with Custom Script Input

on: [workflow_dispatch]
  # push:
  #   branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: pip install 
        run: pip3 install inquirer
        
      - name: Run custom script with Python
        run: python3 -u ${{ github.workspace }}/.github/workflows/prompt.py
        
