name: Your Workflow

on: [workflow_dispatch]

jobs:
  your_job:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Set the overall job timeout
    
    steps:
      - name: Step 1
        run: python -c "print('Executing Step 1')"
      
      - name: Step 2
        run: python -c "print('Executing Step 2')"
      
      - name: User Input Step
        id: user_input
        run: |
          echo "Do you want to proceed? (yes/no): "
          echo "::set-env name=USER_RESPONSE::$(cat)"
      
      - name: Final Step
        if: ${{ needs.your_job.outputs.user_input == 'yes' }}
        run: python -c "print('Executing Final Step')"
