name: Create Issue Workflow

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest
  
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # - name: Install GitHub CLI
      #   run: |
      #     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
      #     sudo apt-add-repository https://cli.github.com/packages
      #     sudo apt update
      #     sudo apt install gh

      - name: Create Issue
        run: |
          gh issue create -t "Confirm Docker Build" -b "Please comment with 'yes' or 'no' to confirm Docker build."
