name: Deploy Workflow

on: [workflow_dispatch]
  # workflow_run:
  #   workflows: ["CI Workflow"]
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://example.com
      # You can configure more environment settings and protections here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Prompt for approval
        if: github.actor == 'your-username'
        run: |
          echo "Do you want to proceed with the deployment? (yes/no)"
          read -r USER_INPUT
          echo "User input is: $USER_INPUT"
          echo "URL: ${{ secrets.DEPLOYMENT_URL }}"
          echo "Proceeding to the next step..."

      - name: Run next step only if user chooses "yes"
        if: env.USER_INPUT == 'yes'
        run: |
          # Your "next step" commands here
          # (e.g., build your code, deploy to production)
          echo "Building and deploying..."
          # ... replace with your actual commands ...

      - name: Skip next step if user chooses "no"
        if: env.USER_INPUT == 'no'
        run: |
          echo "Skipping build and deployment as requested."

      - name: Final step (runs regardless of user choice)
        run: |
          echo "This step runs regardless of the user's response."
