name: tom

on: [pull_request]

jobs:
  approval:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Run approval script
      run: python3 -u ${{ github.workspace }}/.github/workflows/tom.py

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
