name: Trigger workflow

on: [workflow_dispatch]

jobs:
  build:
   runs-on: [ubuntu-latest]

   steps:

    - name: Install inquirer
      run: npm install inquirer@5.5.3 --save-dev
    
    - name: Run custom script with interactive prompts
      uses: actions/github-script@v6
      with:
        script: |
         const inquirer = await import('inquirer');

         const { proceed } = await inquirer.prompt({
         type: 'confirm',
         name: 'proceed',
         message: 'Do you want to proceed further?',
          });

         if (proceed) {
         console.log('Proceeding...');
          } else {
          await github.actions.cancelWorkflowRun(context.workflowRunId);
           }
  
