name: tom

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Enter "yes" or "no"'
        required: true

jobs:
  process_input:
    runs-on: ubuntu-latest

    steps:
    - name: Check user input
      run: |
        if [ "${{ github.event.inputs.user_input }}" = "yes" ]; then
          echo "User selected 'yes'"
          # Add your 'yes' specific actions or commands here
        elif [ "${{ github.event.inputs.user_input }}" = "no" ]; then
          echo "User selected 'no'"
          # Add your 'no' specific actions or commands here
        else
          echo "Invalid input. Please enter 'yes' or 'no'."
          exit 1
        fi
