name: Docker Build Workflow

on: [workflow_dispatch]
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Install GitHub CLI
      #   run: |
      #     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
      #     sudo apt-add-repository https://cli.github.com/packages
      #     sudo apt update
      #     sudo apt install gh


      - name: Get User Input
        id: get-input
        run: |
          comment=$(gh issue view 1 --json body -q .body)
          echo "::set-output name=comment::$comment"

      - name: Docker Build
        if: steps.get-input.outputs.comment == 'yes'
        run: |
          # Your Docker build steps go here
          echo "Building Docker image"
