name: test

on:
  workflow_dispatch:
    inputs:
      emp_name:
        description: 'Employee name to check'
        required: true
        type: string

jobs:
  check_employee:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create input issue
        id: create_input_issue
        run: |
          ISSUE_BODY="Please provide input for employee check. Use the format: '/input yes' or '/input no'"
          echo "::set-output name=input_issue_number::$(gh issue create --title 'Input for Employee Check' --body \"$ISSUE_BODY\" --labels 'workflow' | jq -r '.number')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for user input
        id: wait_for_input
        run: echo "Waiting for user input..."
        timeout-minutes: 10  # Adjust the timeout as needed

      - name: Check issue comments
        id: check_input_issue_comments
        run: echo "::set-output name=comments::$(gh issue list-comments ${{ steps.create_input_issue.outputs.input_issue_number }} --json body -q '.[].body')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Process user input
        id: process_input
        run: |
          USER_INPUT=$(echo "$COMMENTS" | grep -oP '/input\s+\K\w+')
          if [ "$USER_INPUT" == 'yes' ]; then
            echo "Proceeding with the job..."
            echo "::set-output name=proceed::true"
          elif [ "$USER_INPUT" == 'no' ]; then
            echo "Aborting the job..."
            echo "::set-output name=proceed::false"
          else
            echo "Invalid input. Exiting."
            echo "::set-output name=proceed::false"
          fi
        env:
          COMMENTS: ${{ steps.check_input_issue_comments.outputs.comments }}

      - name: Print result
        run: |
          PROCEED="${{ steps.process_input.outputs.proceed }}"
          echo "Proceed: $PROCEED"
          if [ "$PROCEED" == 'true' ]; then
            echo "Success! Continue with additional actions."
          else
            echo "Job aborted. Exiting."
            exit 1
          fi
