name: Deploy Workflow

on:
   [workflow_dispatch]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prompt user to proceed
        uses: matrix-input@v2
        with:
          matrix: |
            proceed: [yes, no]
          prompt: Do you want to proceed with the build? (y/N)

      - name: Run next step only if user chooses "yes"
        if: ${{ matrix.proceed == 'yes' }}
        run: |
          # Your "next step" commands here
          # (e.g., build your code, deploy to production)
          echo "Building and deploying..."
          # ... replace with your actual commands ...

      - name: Skip next step if user chooses "no"
        if: ${{ matrix.proceed == 'no' }}
        run: |
          echo "Skipping build and deployment as requested."

      - name: Final step (runs regardless of user choice)
        run: |
          echo "This step runs regardless of the user's response."
