name: Docker Build Workflow

on: [workflow_dispatch]
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get User Input
        id: get-input
        run: |
          comment=$(gh issue view <issue-number> --json body -q .body)
          echo "::set-output name=comment::$comment"

      - name: Docker Build
        if: steps.get-input.outputs.comment == 'yes'
        run: |
          # Your Docker build steps go here
          echo "Building Docker image"
