name: tom
on:
  workflow_dispatch:

jobs:
  get-collaborators:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
                    
      - name: Get Collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 -u ${{workspace.github}}./github/workflows/tom.py
         
