name: CI/CD Docker Pipeline

on: [workflow_dispatch]
  # push:
  #   branches:
  #     - main

jobs:
  publish_to_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read pipeline.json
        id: read-json
        run: echo "::set-output name=json::$(cat pipeline.json)"

      # - name: Set up Docker
      #   uses: actions/setup-docker@v2

      # - name: Log in to Docker Registry
      #   run: |
      #     # Extract registry details from JSON
      #     REGISTRY_URL=$(echo "${{ steps.read-json.outputs.json }}" | jq -r '.registry_url')
      #     REGISTRY_USERNAME=$(echo "${{ steps.read-json.outputs.json }}" | jq -r '.registry_username')
      #     REGISTRY_PASSWORD=$(echo "${{ steps.read-json.outputs.json }}" | jq -r '.registry_password')

      #     # Log in to the Docker registry
      #     echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USERNAME --password-stdin $REGISTRY_URL

      # - name: Build and Push Docker Image
      #   run: |
      #     # Extract information from JSON
      #     IMAGE_NAME=$(echo "${{ steps.read-json.outputs.json }}" | jq -r '.image_name')
      #     IMAGE_VERSION=$(echo "${{ steps.read-json.outputs.json }}" | jq -r '.image_version')

      #     # Build Docker image
      #     docker build -t $IMAGE_NAME:$IMAGE_VERSION .

      #     # Push Docker image to the registry
      #     docker push $IMAGE_NAME:$IMAGE_VERSION
