name: tom

on:
  workflow_dispatch:
    inputs:
      username: 
        description: username
        type: string
        required: true

      Repositoryname:
        description: repo name
        type: string
        required: true

      issue_name:
        type: string
        required: true
        
jobs:
  get-collaborators:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pip install 
        run: pip3 install requests

                    
      - name: Get Collaborators
        run: python3 -u ${{ github.workspace }}/.github/workflows/tom.py
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
        
         
