name: External Script Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Environment
        run: echo "Setting up environment"

      - name: Run External Script
        id: external_script
        run: |
          enable_check=$(python -u ${{ github.workspace }}/.github/workflows/prompt.py)
          echo "::set-output name=ENABLE_CHECK::$enable_check"

      - name: Use External Script Output
        run: echo "User chose to enable blue-green check:${{ needs.my_job.outputs.ENABLE_CHECK }}"
