name: Your Workflow

on:
  workflow_dispatch:
    inputs:
      proceed:
        description: 'Proceed? (yes/no)'
        required: true

jobs:
  your_job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: python -c "print('Executing Step 1')"

      - name: Step 2
        run: python -c "print('Executing Step 2')"

      - name: Final Step
        if: ${{ github.event.inputs.proceed == 'yes' }}
        run: python -c "print('Executing Final Step')"
