name: My Workflow with Interactive Input

on:
  workflow_dispatch:
  # Uncomment the following lines if you also want to trigger on push events
  # push:
  #   branches: [main]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prompt for deployment confirmation
        id: confirmation
        uses: js-actions/dialog@v5
        with:
          title: Deployment Confirmation
          body: Do you want to deploy changes to production?  
                          
      - name: Deploy to production (if confirmed)
        if: steps.confirmation.outputs.value == 'deploy'
        run: |
          # Your deployment steps go here
          echo "Deploying to production..."

      - name: Cancel deployment (if not confirmed)
        if: steps.confirmation.outputs.value == 'cancel'
        run: echo "Deployment cancelled."
