name: environment test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: production

    steps:
      - name: Hello world
        run: echo "hello world"
