name: Proceed or Abort?

on: [ workflow_dispatch ]

jobs:
  confirm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: pip install 
        run: pip install github

      - name: Prompt for confirmation
        run: echo "prompt yes or no"
        timeout-minutes: 10
        
        

