name: Proceed or Abort?

on: [ workflow_dispatch ]

jobs:
  confirm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: pip install 
        run: pip install github_actions

      - name: Prompt for confirmation
        id: confirm
        run: |
          python3  maxwell134/test321/.github/workflows/confirmation.py
          exit ${{ steps.confirm.outputs.exit_code }}

      - name: Proceed with action (if confirmed)
        if: ${{ steps.confirm.outputs.exit_code == 0 }}
        run: echo "Hello world"

      - name: Terminate action (if aborted)
        run: exit 1
        if: ${{ steps.confirm.outputs.exit_code == 1 }}
        

