name: Use GitHub Issue Inputs

on:
  issue_comment:
    types:
      - created

jobs:
  process_issue_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract inputs from issue comment
        run: |
          # Extract the comment body
          comment=$(curl -sL "${{ github.event.comment.url }}" | jq -r .body)

          # Parse the comment for specific inputs
          input1=$(echo "$comment" | grep -oP 'Input1: \K[^ ]+')
          input2=$(echo "$comment" | grep -oP 'Input2: \K[^ ]+')
          echo "Input1: $input1"

          # Use the inputs in subsequent steps
          

      - name: Hello pie
        run: echo "Hello pie"




        
          echo "Input2: $input2"
