name: Timeout Example

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User input'
        required: true

jobs:
  process_input:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Process input
      run: |
        if [[ "${{ github.event.inputs.user_input }}" == "approve" ]]; then
          echo "Processing input: approve"
          # Add your logic here
        else
          echo "Processing input: reject"
          # Add your logic here
        fi
