name: GitHub Action with Timeout

on: [workflow_dispatch]

jobs:
  timeout_example:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Python script with timeout
      run: |
        timeout 5m python -u ${{github.workspace}}/.github/workflows/product.py
