name: Timeout Example

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User input'
        required: false

jobs:
  process_input:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Process input
      shell: bash
      run: |
       if [ -z "${{ github.event.inputs.user_input }}" ]; then
         sleep 5s
         exit 1
       fi

