name: Install Python Workflow

on:
  push:
    branches:
      - main

jobs:
  install_python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ['3.8', '3.9', '3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: Maxwell134/test321/.github/actions/python@main
        with:
          python_version: ${{ matrix.python_version }}
