name: Install Python Workflow

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version to install'
        required: true
        default: '3.8'

jobs:
  install_python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ['3.8', '3.9', '3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: bash check
        run: bash --version

      - name: Install Python
        uses: Maxwell134/test321/.github/actions/python@main
        with:
          python_version: ${{ github.event.inputs.python_version || matrix.python_version }}
