name: Sample checker

on: [workflow_dispatch]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install inquirer2
      - name: Run analysis prompt
        run: |
          from inquirer2 import Prompt, Checkbox
          message = "What type of analysis should I run?"
          choices = ["Regression", "Classification", "Both"]
          analysis_type = Prompt(message).execute()
          echo "Running analysis: $analysis_type"
        env:
          ANALYSIS_TYPE: ${{ analysis_type }}
