name: Sample checker

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install questionary
      - name: Run analysis prompt
        shell: bash 
        run: |
          from questionary import prompt
          questions = [
              {
                  'type': 'select',
                  'name': 'analysis_type',
                  'message': 'What type of analysis should I run?',
                  'choices': ['Regression', 'Classification', 'Both']
              }
          ]
          answers = prompt(questions)
          print(f"Running analysis: {answers['analysis_type']}")
        env:
          ANALYSIS_TYPE: ${{ env.ANALYSIS_TYPE }}
