name: GitHub Actions with Python Input

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Enter something'
        required: true
        type: string

jobs:
  python_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set User Input
        id: set_input
        run: echo "::set-output name=user_input::${{ github.event.inputs.user_input }}"

      - name: Run Python Script
        run: python3 {{github.workspace}}/.github/workflows/script.py ${{ steps.set_input.outputs.user_input }}
