name: GitHub Actions with Input Timeout

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Enter something'
        required: true
        type: string

jobs:
  timeout_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: install pip 
        run: pip install inputimeout

      - name: Set User Input
        id: set_input
        run: echo "::set-output name=user_input::${{ github.event.inputs.user_input }}"

      - name: Run Python Script with Timeout
        run: python3 -u ${{ github.workspace }}/.github/workflows/script.py ${{ steps.set_input.outputs.user_input }}
