name: GitHub Actions with Input Timeout

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Enter something'
        required: true
        type: string

jobs:
  timeout_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set Timeout Duration
        id: set_timeout
        run: echo "::set-output name=timeout_duration::60"  # Set the timeout duration in seconds

      - name: Set User Input
        id: set_input
        run: echo "::set-output name=user_input::${{ github.event.inputs.user_input }}"

      - name: Run Script with Timeout
        run: |
          chmod +x ${{ github.workspace }}/.github/workflows/your_script.sh
          timeout_duration=${{ steps.set_timeout.outputs.timeout_duration }}
          user_input="${{ github.event.inputs.user_input }}"
          
          # Implement your timeout logic using the 'timeout' command or other mechanisms
          timeout $timeout_duration ${{ github.workspace }}/.github/workflows/./your_script.sh "$user_input" || echo "Timeout occurred"
