name: Check GitHub Users

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch

jobs:
  check-users:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Check GitHub Users
      run: python3 -u ${{ github.workspace }}/.github/workflows/script.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
